--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/alvin0319/GroupsAPI
build-by-default: true
branches:
- master
projects:
  GroupsAPI:
    path: ""
    libs:
      - src: poggit/libsynql/libasynql
        version: 4.0.0^
...
