--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/alvin0319/GroupsAPI
build-by-default: true
branches:
  - master
projects:
  GroupsAPI:
    path: ""
    lint:
      phpstan: false
    libs:
      - src: poggit/libasynql/libasynql
        version: ^4.0.1
      - src: sof3/await-generator/await-generator
          version: ^3.3.0
...
